In [1]:
# 위스퍼 API는 음성을 잘 받아쓰지만 누가 어떤 말을 했는지는 구분해주지 않는다.
# 화자를 구분하는 pyannote.audio를 사용해보자.

# pip install pyannote.audio
# pip install numpy==1.26
# 관련 사이트 https://pypi.org/project/pyannote-audio/

# 허깅페이스에서 화자 분리 모델 내려받고 사용하려면 토큰이 필요하다.
# 허깅페이스 웹사이트에서 로그인(회원가입) 하고 프로필 로고를 클릭에 setting으로 간다.
# 엑세스 토큰을 발급받아 메모장에 저장 해 둔다.

# 허깅페이스 검색창에 pyannote/speaker-diarization-3.1 를 검색하여 찾아 들어간다.
# 모델을 사용하려면 소속 기관과 웹사이트 정보를 입력해야 한다.
# PERSONAL / I have no website 를 입력한다. Agree and access repository 클릭

# Requirements 부분 확인
# Install pyannote.audio 3.1 with pip install pyannote.audio

# Accept pyannote/segmentation-3.0 user conditions -> 여기 클릭하여 접근권한 설정 
# PERSONAL / I have no website 를 입력한다. Agree and access repository 클릭
# Accept pyannote/speaker-diarization-3.1 user conditions -> 여기 클릭하여 접근권한 설정 
# PERSONAL / I have no website 를 입력한다. Agree and access repository 클릭

# https://huggingface.co/pyannote/speaker-diarization-community-1 -> 여기도 접근권한 설정
# 회사/대학교 PERSONAL / 사용 사례 회의록 작성도구 -> 동의

# Create access token at hf.co/settings/tokens.
# 하단에 Usage 소스코드를 참고하여 만든다.

import os
from dotenv import load_dotenv # pip install python-dotenv
# 최상위 .env에 HUGGING_FACE_TOKEN=엑세스토큰값 입력

load_dotenv()

HUGGING_FACE_TOKEN = os.getenv("HUGGING_FACE_TOKEN")
# print(HUGGING_FACE_TOKEN)

In [2]:
# instantiate the pipeline
from pyannote.audio import Pipeline

pipeline = Pipeline.from_pretrained(
  "pyannote/speaker-diarization-3.1",
  use_auth_token=HUGGING_FACE_TOKEN
)

c:\Aiprojects\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
INFO:speechbrain.utils.quirks:Applied quirks (see `speechbrain.utils.quirks`): [allow_tf32, disable_jit_profiling]
INFO:speechbrain.utils.quirks:Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
C:\Users\MBC320\AppData\Local\Programs\Python\Python312\Lib\inspect.py:1007: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
  if ismodule(module) and hasattr(module, '__file__'):

In [3]:
import torch
# 1. 장치 설정 (CUDA 사용 가능 여부 확인)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

pipeline = pipeline.to(device)

print(f"Using device: {device}")

Using device: cpu

In [4]:
# run the pipeline on an audio file
# diarization = pipeline("audio.wav")
# diarization = pipeline("../audio/싼기타_비싼기타.mp3")

# dump the diarization output to disk using RTTM format
# with open("싼기타_비싼기타.rttm", "w", encoding='utf-8') as rttm:
#     diarization.write_rttm(rttm)

# 3. 오디오 파일 경로 (절대 경로 혹은 상대 경로)
# audio_input = "../audio/싼기타_비싼기타.mp3"

# # 4. 실행 (화자 분리 수행)
# print(f"화자 분리 시작: {audio_input}")
# try:
#     # 파이프라인 실행
#     diarization = diarization_pipeline(audio_input)

#     # 5. RTTM 파일로 저장
#     output_rttm = "싼기타_비싼기타.rttm"
#     with open(output_rttm, "w", encoding='utf-8') as rttm:
#         diarization.write_rttm(rttm)
    
#     print(f"성공! 결과 파일: {output_rttm}")

#     # 간단하게 결과 미리보기
#     for turn, _, speaker in diarization.itertracks(yield_label=True):
#         print(f"[{turn.start:.1f}s - {turn.end:.1f}s] Speaker: {speaker}")

# except Exception as e:
#     print(f"실행 중 오류 발생: {e}")
#     print("해결 팁: 터미널에서 'pip uninstall torchcodec'을 실행했는지 확인하세요.")

# 3. 오디오 파일 경로 및 실행
if pipeline:
    audio_input = "../audio/싼기타_비싼기타.mp3"
    print(f"화자 분리 시작: {audio_input}")
    
    try:
        # 파이프라인 실행
        diarization = pipeline(audio_input)

        # 4. RTTM 파일로 저장
        output_rttm = "싼기타_비싼기타.rttm"
        with open(output_rttm, "w", encoding='utf-8') as rttm:
            diarization.write_rttm(rttm)
        
        print(f"성공! 결과 파일: {output_rttm}")

        # 간단하게 결과 미리보기
        for turn, _, speaker in diarization.itertracks(yield_label=True):
            print(f"[{turn.start:.1f}s - {turn.end:.1f}s] Speaker: {speaker}")

    except Exception as e:
        print(f"실행 중 오류 발생: {e}")
        print("해결 팁: 터미널에서 'pip uninstall torchcodec'을 실행했는지 확인하세요.")
else:
    print("변수 'diarization_pipeline'이 생성되지 않아 실행을 중단합니다.")

화자 분리 시작: ../audio/싼기타_비싼기타.mp3

c:\Aiprojects\venv\Lib\site-packages\pyannote\audio\models\blocks\pooling.py:104: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at ..\aten\src\ATen\native\ReduceOps.cpp:1807.)
  std = sequences.std(dim=-1, correction=1)
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(
c:\Aiprojects\venv\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:71: UserWarning: The MPEG_LAYER_III subtype is unknown to TorchAudio. As a result, the bits_per_sample attribute will be set to 0. If you are seeing this warning, please report by opening an issue on github (after checking for existing/closed ones). You may otherwise ignore this warning.
  warnings.warn(

성공! 결과 파일: 싼기타_비싼기타.rttm
[1.0s - 6.8s] Speaker: SPEAKER_01
[7.4s - 11.4s] Speaker: SPEAKER_01
[11.8s - 16.7s] Speaker: SPEAKER_01
[17.2s - 27.9s] Speaker: SPEAKER_01
[28.7s - 30.2s] Speaker: SPEAKER_01
[32.4s - 33.2s] Speaker: SPEAKER_00
[33.5s - 37.1s] Speaker: SPEAKER_00
[37.6s - 41.4s] Speaker: SPEAKER_00
[41.6s - 42.7s] Speaker: SPEAKER_00
[41.6s - 42.5s] Speaker: SPEAKER_01
[42.7s - 44.0s] Speaker: SPEAKER_01
[45.8s - 46.4s] Speaker: SPEAKER_00
[46.8s - 50.5s] Speaker: SPEAKER_00
[51.0s - 59.5s] Speaker: SPEAKER_00
[60.0s - 64.9s] Speaker: SPEAKER_00
[65.5s - 67.1s] Speaker: SPEAKER_00
[67.2s - 73.7s] Speaker: SPEAKER_01
[74.0s - 79.0s] Speaker: SPEAKER_01
[79.2s - 82.8s] Speaker: SPEAKER_01
[84.7s - 87.1s] Speaker: SPEAKER_00
[87.3s - 91.2s] Speaker: SPEAKER_00
[91.8s - 97.5s] Speaker: SPEAKER_00
[97.9s - 102.6s] Speaker: SPEAKER_00
[103.5s - 114.6s] Speaker: SPEAKER_01
[115.1s - 117.5s] Speaker: SPEAKER_01
[119.8s - 127.5s] Speaker: SPEAKER_00
[128.2s - 133.7s] Speaker: SPEAKER_00
[134.2s - 138.7s] Speaker: SPEAKER_00
[139.4s - 142.7s] Speaker: SPEAKER_01
[143.2s - 143.7s] Speaker: SPEAKER_01
[144.0s - 146.7s] Speaker: SPEAKER_01
[147.2s - 169.0s] Speaker: SPEAKER_01
[170.9s - 176.1s] Speaker: SPEAKER_00
[176.5s - 184.7s] Speaker: SPEAKER_00
[185.0s - 192.3s] Speaker: SPEAKER_00
[192.3s - 193.7s] Speaker: SPEAKER_01
[192.8s - 193.5s] Speaker: SPEAKER_00
[193.8s - 216.6s] Speaker: SPEAKER_01
[218.6s - 222.9s] Speaker: SPEAKER_00
[223.4s - 228.9s] Speaker: SPEAKER_00
[229.6s - 233.0s] Speaker: SPEAKER_00
[233.4s - 237.8s] Speaker: SPEAKER_00
[238.1s - 238.1s] Speaker: SPEAKER_00
[238.1s - 238.7s] Speaker: SPEAKER_01
[238.2s - 239.4s] Speaker: SPEAKER_00
[239.9s - 240.7s] Speaker: SPEAKER_01
[240.3s - 241.0s] Speaker: SPEAKER_00
[241.0s - 247.9s] Speaker: SPEAKER_01
[248.2s - 251.3s] Speaker: SPEAKER_01
[253.7s - 257.7s] Speaker: SPEAKER_00
[258.1s - 262.3s] Speaker: SPEAKER_00
[262.7s - 267.6s] Speaker: SPEAKER_00
[268.1s - 271.5s] Speaker: SPEAKER_00
[272.1s - 276.2s] Speaker: SPEAKER_01
[276.7s - 282.9s] Speaker: SPEAKER_01
[283.3s - 290.8s] Speaker: SPEAKER_01
[291.0s - 298.4s] Speaker: SPEAKER_01
[298.8s - 304.6s] Speaker: SPEAKER_01
[307.0s - 311.3s] Speaker: SPEAKER_00
[311.6s - 318.8s] Speaker: SPEAKER_00
[319.5s - 326.0s] Speaker: SPEAKER_00
[326.4s - 331.1s] Speaker: SPEAKER_01
[331.4s - 335.5s] Speaker: SPEAKER_01
[337.5s - 342.7s] Speaker: SPEAKER_00
[343.2s - 347.2s] Speaker: SPEAKER_00
[347.6s - 352.3s] Speaker: SPEAKER_00
[352.6s - 355.9s] Speaker: SPEAKER_00
[356.2s - 364.0s] Speaker: SPEAKER_01
[366.0s - 366.4s] Speaker: SPEAKER_00
[366.8s - 371.6s] Speaker: SPEAKER_00
[371.9s - 378.6s] Speaker: SPEAKER_00
[379.1s - 381.4s] Speaker: SPEAKER_00
[382.2s - 383.7s] Speaker: SPEAKER_01
[385.7s - 387.6s] Speaker: SPEAKER_00
[387.8s - 390.7s] Speaker: SPEAKER_00
[391.1s - 394.9s] Speaker: SPEAKER_00
[395.3s - 397.2s] Speaker: SPEAKER_00
[397.6s - 399.1s] Speaker: SPEAKER_01
[401.4s - 403.6s] Speaker: SPEAKER_00
[404.0s - 406.6s] Speaker: SPEAKER_00
[407.3s - 408.3s] Speaker: SPEAKER_01
[410.1s - 412.0s] Speaker: SPEAKER_00
[412.4s - 414.0s] Speaker: SPEAKER_00
[414.5s - 417.5s] Speaker: SPEAKER_00
[417.8s - 421.2s] Speaker: SPEAKER_01
[423.6s - 424.4s] Speaker: SPEAKER_00
[424.7s - 428.3s] Speaker: SPEAKER_00
[428.5s - 429.3s] Speaker: SPEAKER_00

In [5]:
import pandas as pd
rttm_path = "./싼기타_비싼기타.rttm"

df_rttm = pd.read_csv(
    rttm_path,      # rttm 파일 경로
    sep=' ',        # 구분자는 띄어쓰기
    header=None,    # 헤더는 없음
    names=['type', 'file', 'chnl', 'start', 'duration', 'C1', 'C2', 'speaker_id', 'C3', 'C4'] 
)

display(df_rttm)

       type      file  chnl    start  duration  C1  C2  speaker_id  C3  C4
0   SPEAKER  싼기타_비싼기타     1    0.993     5.805 NaN NaN  SPEAKER_01 NaN NaN
1   SPEAKER  싼기타_비싼기타     1    7.405     3.983 NaN NaN  SPEAKER_01 NaN NaN
2   SPEAKER  싼기타_비싼기타     1   11.759     4.927 NaN NaN  SPEAKER_01 NaN NaN
3   SPEAKER  싼기타_비싼기타     1   17.210    10.665 NaN NaN  SPEAKER_01 NaN NaN
4   SPEAKER  싼기타_비싼기타     1   28.668     1.536 NaN NaN  SPEAKER_01 NaN NaN
..      ...       ...   ...      ...       ...  ..  ..         ...  ..  ..
83  SPEAKER  싼기타_비싼기타     1  414.481     2.970 NaN NaN  SPEAKER_00 NaN NaN
84  SPEAKER  싼기타_비싼기타     1  417.755     3.476 NaN NaN  SPEAKER_01 NaN NaN
85  SPEAKER  싼기타_비싼기타     1  423.644     0.776 NaN NaN  SPEAKER_00 NaN NaN
86  SPEAKER  싼기타_비싼기타     1  424.741     3.527 NaN NaN  SPEAKER_00 NaN NaN
87  SPEAKER  싼기타_비싼기타     1  428.504     0.844 NaN NaN  SPEAKER_00 NaN NaN

[88 rows x 10 columns]

In [6]:
# start + duration을 end로 변환
df_rttm['end'] = df_rttm['start'] + df_rttm['duration']

display(df_rttm)

,type,file,chnl,start,duration,C1,C2,speaker_id,C3,C4,end
0,SPEAKER,싼기타_비싼기타,1,0.993,5.805,NaN,NaN,SPEAKER_01,NaN,NaN,6.798
1,SPEAKER,싼기타_비싼기타,1,7.405,3.983,NaN,NaN,SPEAKER_01,NaN,NaN,11.388
2,SPEAKER,싼기타_비싼기타,1,11.759,4.927,NaN,NaN,SPEAKER_01,NaN,NaN,16.686
3,SPEAKER,싼기타_비싼기타,1,17.210,10.665,NaN,NaN,SPEAKER_01,NaN,NaN,27.875
4,SPEAKER,싼기타_비싼기타,1,28.668,1.536,NaN,NaN,SPEAKER_01,NaN,NaN,30.204
...,...,...,...,...,...,...,...,...,...,...,...
83,SPEAKER,싼기타_비싼기타,1,414.481,2.970,NaN,NaN,SPEAKER_00,NaN,NaN,417.451
84,SPEAKER,싼기타_비싼기타,1,417.755,3.476,NaN,NaN,SPEAKER_01,NaN,NaN,421.231
85,SPEAKER,싼기타_비싼기타,1,423.644,0.776,NaN,NaN,SPEAKER_00,NaN,NaN,424.420
86,SPEAKER,싼기타_비싼기타,1,424.741,3.527,NaN,NaN,SPEAKER_00,NaN,NaN,428.268
87,SPEAKER,싼기타_비싼기타,1,428.504,0.844,NaN,NaN,SPEAKER_00,NaN,NaN,429.348

In [7]:
df_rttm["number"] = None	# number 열 만들고 None으로 초기화
df_rttm.at[0, "number"] = 0

display(df_rttm)

,type,file,chnl,start,duration,C1,C2,speaker_id,C3,C4,end,number
0,SPEAKER,싼기타_비싼기타,1,0.993,5.805,NaN,NaN,SPEAKER_01,NaN,NaN,6.798,0
1,SPEAKER,싼기타_비싼기타,1,7.405,3.983,NaN,NaN,SPEAKER_01,NaN,NaN,11.388,None
2,SPEAKER,싼기타_비싼기타,1,11.759,4.927,NaN,NaN,SPEAKER_01,NaN,NaN,16.686,None
3,SPEAKER,싼기타_비싼기타,1,17.210,10.665,NaN,NaN,SPEAKER_01,NaN,NaN,27.875,None
4,SPEAKER,싼기타_비싼기타,1,28.668,1.536,NaN,NaN,SPEAKER_01,NaN,NaN,30.204,None
...,...,...,...,...,...,...,...,...,...,...,...,...
83,SPEAKER,싼기타_비싼기타,1,414.481,2.970,NaN,NaN,SPEAKER_00,NaN,NaN,417.451,None
84,SPEAKER,싼기타_비싼기타,1,417.755,3.476,NaN,NaN,SPEAKER_01,NaN,NaN,421.231,None
85,SPEAKER,싼기타_비싼기타,1,423.644,0.776,NaN,NaN,SPEAKER_00,NaN,NaN,424.420,None
86,SPEAKER,싼기타_비싼기타,1,424.741,3.527,NaN,NaN,SPEAKER_00,NaN,NaN,428.268,None
87,SPEAKER,싼기타_비싼기타,1,428.504,0.844,NaN,NaN,SPEAKER_00,NaN,NaN,429.348,None

In [8]:
for i in range(1, len(df_rttm)):
    if df_rttm.at[i, "speaker_id"] != df_rttm.at[i-1, "speaker_id"]:
        df_rttm.at[i, "number"] = df_rttm.at[i-1, "number"] + 1
    else:
        df_rttm.at[i, "number"] = df_rttm.at[i-1, "number"]

display(df_rttm.head(10))

,type,file,chnl,start,duration,C1,C2,speaker_id,C3,C4,end,number
0,SPEAKER,싼기타_비싼기타,1,0.993,5.805,NaN,NaN,SPEAKER_01,NaN,NaN,6.798,0
1,SPEAKER,싼기타_비싼기타,1,7.405,3.983,NaN,NaN,SPEAKER_01,NaN,NaN,11.388,0
2,SPEAKER,싼기타_비싼기타,1,11.759,4.927,NaN,NaN,SPEAKER_01,NaN,NaN,16.686,0
3,SPEAKER,싼기타_비싼기타,1,17.210,10.665,NaN,NaN,SPEAKER_01,NaN,NaN,27.875,0
4,SPEAKER,싼기타_비싼기타,1,28.668,1.536,NaN,NaN,SPEAKER_01,NaN,NaN,30.204,0
5,SPEAKER,싼기타_비싼기타,1,32.414,0.759,NaN,NaN,SPEAKER_00,NaN,NaN,33.173,1
6,SPEAKER,싼기타_비싼기타,1,33.545,3.561,NaN,NaN,SPEAKER_00,NaN,NaN,37.106,1
7,SPEAKER,싼기타_비싼기타,1,37.628,3.763,NaN,NaN,SPEAKER_00,NaN,NaN,41.391,1
8,SPEAKER,싼기타_비싼기타,1,41.611,1.097,NaN,NaN,SPEAKER_00,NaN,NaN,42.708,1
9,SPEAKER,싼기타_비싼기타,1,41.645,0.810,NaN,NaN,SPEAKER_01,NaN,NaN,42.455,2

In [9]:
df_rttm_grouped = df_rttm.groupby("number").agg(
    start=pd.NamedAgg(column='start', aggfunc='min'),
    end=pd.NamedAgg(column='end', aggfunc='max'),
    speaker_id=pd.NamedAgg(column='speaker_id', aggfunc='first')
)

display(df_rttm_grouped)

          start      end  speaker_id
number
0         0.993   30.204  SPEAKER_01
1        32.414   42.708  SPEAKER_00
2        41.645   44.024  SPEAKER_01
3        45.813   67.109  SPEAKER_00
4        67.227   82.786  SPEAKER_01
5        84.659  102.564  SPEAKER_00
6       103.492  117.532  SPEAKER_01
7       119.759  138.676  SPEAKER_00
8       139.351  168.967  SPEAKER_01
9       170.907  192.321  SPEAKER_00
10      192.322  193.689  SPEAKER_01
11      192.760  193.503  SPEAKER_00
12      193.823  216.571  SPEAKER_01
13      218.579  238.120  SPEAKER_00
14      238.120  238.677  SPEAKER_01
15      238.188  239.352  SPEAKER_00
16      239.858  240.651  SPEAKER_01
17      240.297  241.006  SPEAKER_00
18      241.040  251.334  SPEAKER_01
19      253.696  271.550  SPEAKER_00
20      272.140  304.557  SPEAKER_01
21      306.970  326.022  SPEAKER_00
22      326.360  335.472  SPEAKER_01
23      337.548  355.925  SPEAKER_00
24      356.245  363.974  SPEAKER_01
25      365.982  381.423  SPEAKER_00
26      382.165  383.734  SPEAKER_01
27      385.726  397.184  SPEAKER_00
28      397.623  399.108  SPEAKER_01
29      401.437  406.601  SPEAKER_00
30      407.326  408.338  SPEAKER_01
31      410.093  417.451  SPEAKER_00
32      417.755  421.231  SPEAKER_01
33      423.644  429.348  SPEAKER_00

In [10]:
df_rttm_grouped["duration"] = df_rttm_grouped["end"] - df_rttm_grouped["start"]
df_rttm_grouped = df_rttm_grouped.reset_index(drop=True)
display(df_rttm_grouped)

      start      end  speaker_id  duration
0     0.993   30.204  SPEAKER_01    29.211
1    32.414   42.708  SPEAKER_00    10.294
2    41.645   44.024  SPEAKER_01     2.379
3    45.813   67.109  SPEAKER_00    21.296
4    67.227   82.786  SPEAKER_01    15.559
5    84.659  102.564  SPEAKER_00    17.905
6   103.492  117.532  SPEAKER_01    14.040
7   119.759  138.676  SPEAKER_00    18.917
8   139.351  168.967  SPEAKER_01    29.616
9   170.907  192.321  SPEAKER_00    21.414
10  192.322  193.689  SPEAKER_01     1.367
11  192.760  193.503  SPEAKER_00     0.743
12  193.823  216.571  SPEAKER_01    22.748
13  218.579  238.120  SPEAKER_00    19.541
14  238.120  238.677  SPEAKER_01     0.557
15  238.188  239.352  SPEAKER_00     1.164
16  239.858  240.651  SPEAKER_01     0.793
17  240.297  241.006  SPEAKER_00     0.709
18  241.040  251.334  SPEAKER_01    10.294
19  253.696  271.550  SPEAKER_00    17.854
20  272.140  304.557  SPEAKER_01    32.417
21  306.970  326.022  SPEAKER_00    19.052
22  326.360  335.472  SPEAKER_01     9.112
23  337.548  355.925  SPEAKER_00    18.377
24  356.245  363.974  SPEAKER_01     7.729
25  365.982  381.423  SPEAKER_00    15.441
26  382.165  383.734  SPEAKER_01     1.569
27  385.726  397.184  SPEAKER_00    11.458
28  397.623  399.108  SPEAKER_01     1.485
29  401.437  406.601  SPEAKER_00     5.164
30  407.326  408.338  SPEAKER_01     1.012
31  410.093  417.451  SPEAKER_00     7.358
32  417.755  421.231  SPEAKER_01     3.476
33  423.644  429.348  SPEAKER_00     5.704

In [11]:
df_rttm_grouped.to_csv(
    "싼기타_비싼기타_rttm.csv",
    sep=',',
    index=False
)